name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          TARGET: ~/nku-deploy
    
      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/nku-deploy
            npm ci
            npm run build
            cd ..
            pm2 stop nku
            rm -r ~/nku
            mv nku-deploy nku
            pm2 start nku
